// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Application-wide error type.
 */
export type AppError = { "code": "io", source: string, detail: string | null, } | { "code": "git_command", command: string, stderr: string, stdout: string, detail: string | null, } | { "code": "git_version_too_old", found: string, required: string, } | { "code": "invalid_repo", path: string, } | { "code": "operation_cancelled" } | { "code": "credential_cancelled" } | { "code": "parse", message: string, } | { "code": "internal", message: string, } | { "code": "not_implemented", feature: string, };
