// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BranchInfo = { name: string, full_name: string, upstream: string | null, ahead: number, behind: number, current: boolean, detached: boolean, };
