// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CommitInfo = { hash: string, short_hash: string, author: string, email: string, date: string, message: string, refs: Array<string>, parents: Array<string>, };
