// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiffFile } from "./DiffFile";
import type { DiffSource } from "./DiffSource";

export type DiffModel = { source: DiffSource, old_revision: string | null, new_revision: string | null, files: Array<DiffFile>, };
