// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiffLineKind } from "./DiffLineKind";

export type DiffLine = { content: string, left_no: number | null, right_no: number | null, kind: DiffLineKind, };
