// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiffLine } from "./DiffLine";

export type DiffHunk = { old_start: number, old_count: number, new_start: number, new_count: number, header: string, lines: Array<DiffLine>, };
