// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiffHunk } from "./DiffHunk";

export type DiffFile = { old_path: string | null, new_path: string | null, similarity: number | null, binary: boolean, hunks: Array<DiffHunk>, };
