// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FileStatus = { path: string, status: string, orig_path: string | null, submodule: boolean, staged: boolean, unstaged: boolean, untracked: boolean, skipped: boolean, conflict: boolean, };
