// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RebaseState = { state: string, current_step: number, total_steps: number, current_commit: string | null, };
