// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ReflogEntry = { hash: string, short_hash: string, ref_name: string, message: string, date: string, author: string, };
