// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RemoteInfo = { name: string, url: string, fetch_url: string, push_url: string, };
