// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type StashEntry = { index: number, message: string, branch: string | null, date: string, };
