// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileStatus } from "./FileStatus";

/**
 * Cached display snapshot for one repository. Per PLAN §4.3 the cache only
 * accelerates display — the `.git` dir and worktree remain the source of
 * truth, and every external event invalidates it.
 */
export type StatusSnapshot = { generation: bigint, 
/**
 * Duration of the git re-read that produced this snapshot (SLA 埋点).
 */
duration_ms: bigint, status: Array<FileStatus>, };
