// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TagInfo = { name: string, full_name: string, target: string, tagger: string | null, date: string | null, message: string | null, };
