// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	/**  Return the detected git capabilities as JSON. */
	gitVersion: () => __TAURI_INVOKE<string>("git_version"),
	/**  Greet command (legacy from template). */
	greet: (name: string) => __TAURI_INVOKE<string>("greet", { name }),
	repoOpen: (path: string) => __TAURI_INVOKE<[RepoId_Serialize, string]>("repo_open", { path }),
	repoClose: (id: RepoId_Deserialize) => __TAURI_INVOKE<null>("repo_close", { id }),
	repoList: () => __TAURI_INVOKE<([RepoId_Serialize, string])[]>("repo_list"),
	gitStatus: (id: RepoId_Deserialize) => __TAURI_INVOKE<FileStatus_Serialize[]>("git_status", { id }),
	gitStage: (id: RepoId_Deserialize, paths: string[]) => __TAURI_INVOKE<null>("git_stage", { id, paths }),
	gitUnstage: (id: RepoId_Deserialize, paths: string[]) => __TAURI_INVOKE<null>("git_unstage", { id, paths }),
	/**
	 *  Discard changes for the given paths, with a recovery snapshot taken
	 *  beforehand (PLAN §4.7 轨道 A) so the operation is undoable.
	 * 
	 *  Scope semantics per path (classification from a fresh status under the
	 *  write gate):
	 *  - untracked → physically deleted (snapshot holds a copy);
	 *  - unmerged (conflict) → full reset to HEAD (`restore --source=HEAD -S -W`);
	 *  - tracked, scope=worktree → `git restore` (staged state kept);
	 *  - tracked, scope=all → `git restore --source=HEAD -S -W` (staged dropped).
	 * 
	 *  Returns the snapshot id for the undo entry, or `None` when nothing was
	 *  discardable. On failure the snapshot is rolled back.
	 */
	gitDiscard: (id: RepoId_Deserialize, paths: string[], scope: string) => __TAURI_INVOKE<string | null>("git_discard", { id, paths, scope }),
	gitCommit: (id: RepoId_Deserialize, message: string, amend: boolean, noVerify: boolean) => __TAURI_INVOKE<CommitResult>("git_commit", { id, message, amend, noVerify }),
	/**
	 *  HEAD commit message (subject + body) for the Amend flow; `None` when
	 *  HEAD is unborn.
	 */
	gitHeadMessage: (id: RepoId_Deserialize) => __TAURI_INVOKE<string | null>("git_head_message", { id }),
	/**  Append paths to `.gitignore` (right-click "ignore" action). */
	gitIgnorePaths: (id: RepoId_Deserialize, paths: string[]) => __TAURI_INVOKE<null>("git_ignore_paths", { id, paths }),
	gitLog: (id: RepoId_Deserialize, limit: number, offset: number, paths: string[] | null) => __TAURI_INVOKE<CommitInfo[]>("git_log", { id, limit, offset, paths }),
	gitDiff: (id: RepoId_Deserialize, source: string, oldRev: string | null, newRev: string | null, paths: string[] | null) => __TAURI_INVOKE<DiffModel>("git_diff", { id, source, oldRev, newRev, paths }),
	gitBranches: (id: RepoId_Deserialize) => __TAURI_INVOKE<BranchInfo[]>("git_branches", { id }),
	gitCheckoutBranch: (id: RepoId_Deserialize, name: string) => __TAURI_INVOKE<null>("git_checkout_branch", { id, name }),
	recoveryList: (id: RepoId_Deserialize) => __TAURI_INVOKE<RecoveryEntry[]>("recovery_list", { id }),
	recoveryRestore: (id: RepoId_Deserialize, snapshotId: string) => __TAURI_INVOKE<null>("recovery_restore", { id, snapshotId }),
	recoveryDelete: (id: RepoId_Deserialize, snapshotId: string) => __TAURI_INVOKE<null>("recovery_delete", { id, snapshotId }),
	workspaceRecents: () => __TAURI_INVOKE<RecentRepo[]>("workspace_recents"),
	workspaceTouchRecent: (path: string, name: string) => __TAURI_INVOKE<null>("workspace_touch_recent", { path, name }),
	workspaceForgetRecent: (path: string) => __TAURI_INVOKE<null>("workspace_forget_recent", { path }),
	workspaceLoadState: (repoPath: string) => __TAURI_INVOKE<{
	view?: string | null,
	filter?: string,
	sidebar_collapsed?: string[],
	selected_file?: SelectedFile | null,
	/**  Workspace list mode: `list` (flat sections) or `tree` (path tree). */
	view_mode?: string | null,
	/**  Collapsed directory ids in tree mode. */
	tree_collapsed?: string[],
} | null>("workspace_load_state", { repoPath }),
	workspaceSaveState: (repoPath: string, state: RepoUiState_Deserialize) => __TAURI_INVOKE<null>("workspace_save_state", { repoPath, state }),
	/**  Load the full groups file (groups + per-repo metadata). */
	workspaceGroups: () => __TAURI_INVOKE<GroupsFile_Serialize>("workspace_groups"),
	/**  Create a group (`id: None`) or rename an existing one (`id: Some`). */
	workspaceUpsertGroup: (id: string | null, name: string) => __TAURI_INVOKE<RepoGroup>("workspace_upsert_group", { id, name }),
	/**  Delete a group; member repos fall back to ungrouped (stars are kept). */
	workspaceDeleteGroup: (id: string) => __TAURI_INVOKE<null>("workspace_delete_group", { id }),
	/**
	 *  Set the organizational metadata of one repo (group membership and/or
	 *  star; full replace).
	 */
	workspaceUpdateRepo: (path: string, meta: RepoMeta_Deserialize) => __TAURI_INVOKE<null>("workspace_update_repo", { path, meta }),
};

/** Events */
export const events = {
	appOpenPaths: makeEvent<AppOpenPaths>("app-open-paths"),
	repoChanged: makeEvent<RepoChanged_Deserialize>("repo-changed"),
};

/* Types */
/**  Application-wide error type. */
export type AppError = { code: "io"; source: string; detail: string | null } | { code: "git_command"; command: string; stderr: string; stdout: string; detail: string | null } | { code: "git_version_too_old"; found: string; required: string } | { code: "invalid_repo"; path: string } | { code: "operation_cancelled" } | { code: "credential_cancelled" } | { code: "parse"; message: string } | { code: "internal"; message: string } | { code: "not_implemented"; feature: string };

/**
 *  Emitted to the frontend when a second app instance was launched with
 *  repository paths on its command line (single-instance plugin, P2).
 */
export type AppOpenPaths = {
	paths: string[],
};

export type BranchInfo = {
	name: string,
	full_name: string,
	upstream: string | null,
	ahead: number,
	behind: number,
	current: boolean,
	detached: boolean,
};

export type CommitInfo = {
	hash: string,
	short_hash: string,
	author: string,
	email: string,
	date: string,
	message: string,
	refs: string[],
	parents: string[],
};

export type CommitResult = {
	hash: string,
	short_hash: string,
	message: string,
};

export type DiffFile = {
	old_path: string | null,
	new_path: string | null,
	similarity: number | null,
	binary: boolean,
	hunks: DiffHunk[],
};

export type DiffHunk = {
	old_start: number,
	old_count: number,
	new_start: number,
	new_count: number,
	header: string,
	lines: DiffLine[],
};

export type DiffLine = {
	content: string,
	left_no: number | null,
	right_no: number | null,
	kind: DiffLineKind,
};

export type DiffLineKind = "context" | "add" | "remove" | "header";

export type DiffModel = {
	source: DiffSource,
	old_revision: string | null,
	new_revision: string | null,
	files: DiffFile[],
};

export type DiffSource = "worktree" | "staged" | "commit" | "stash";

export type FileStatus = FileStatus_Serialize | FileStatus_Deserialize;

export type FileStatus_Deserialize = {
	path: string,
	status: string,
	orig_path: string | null,
	submodule: boolean,
	/**  Submodule with modified content (porcelain v2 `sub = S`). */
	submodule_dirty: boolean,
	/**  Submodule whose checked-in commit differs from the index (`sub = M`). */
	submodule_commit_changed: boolean,
	/**
	 *  The worktree change consists only of line-ending differences
	 *  (CRLF/LF); detected via the `--ignore-cr-at-eol` numstat diff.
	 */
	eol_only: boolean,
	staged: boolean,
	unstaged: boolean,
	untracked: boolean,
	/**  skip-worktree (porcelain v2 XY contains `S`). */
	skipped: boolean,
	conflict: boolean,
};

export type FileStatus_Serialize = {
	path: string,
	status: string,
	orig_path?: string | null,
	submodule: boolean,
	/**  Submodule with modified content (porcelain v2 `sub = S`). */
	submodule_dirty: boolean,
	/**  Submodule whose checked-in commit differs from the index (`sub = M`). */
	submodule_commit_changed: boolean,
	/**
	 *  The worktree change consists only of line-ending differences
	 *  (CRLF/LF); detected via the `--ignore-cr-at-eol` numstat diff.
	 */
	eol_only: boolean,
	staged: boolean,
	unstaged: boolean,
	untracked: boolean,
	/**  skip-worktree (porcelain v2 XY contains `S`). */
	skipped: boolean,
	conflict: boolean,
};

/**
 *  `workspaces/groups.json` — the long-lived organizational layer over the
 *  repo collection. Unlike `recents.json` (bounded recently-opened list),
 *  group membership and stars must survive recents truncation, hence a
 *  separate file (PLAN P3.5).
 */
export type GroupsFile = GroupsFile_Serialize | GroupsFile_Deserialize;

/**
 *  `workspaces/groups.json` — the long-lived organizational layer over the
 *  repo collection. Unlike `recents.json` (bounded recently-opened list),
 *  group membership and stars must survive recents truncation, hence a
 *  separate file (PLAN P3.5).
 */
export type GroupsFile_Deserialize = {
	version?: number,
	groups?: RepoGroup[],
	/**
	 *  Resolved repo path → metadata. Keys use the resolved worktree root
	 *  (same normalization as `RepoId`) to avoid Windows case ambiguity.
	 */
	repos?: { [key in string]: RepoMeta_Deserialize },
};

/**
 *  `workspaces/groups.json` — the long-lived organizational layer over the
 *  repo collection. Unlike `recents.json` (bounded recently-opened list),
 *  group membership and stars must survive recents truncation, hence a
 *  separate file (PLAN P3.5).
 */
export type GroupsFile_Serialize = {
	version: number,
	groups: RepoGroup[],
	/**
	 *  Resolved repo path → metadata. Keys use the resolved worktree root
	 *  (same normalization as `RepoId`) to avoid Windows case ambiguity.
	 */
	repos: { [key in string]: RepoMeta_Serialize },
};

export type RecentRepo = {
	path: string,
	name: string,
	/**  Unix timestamp (seconds) of the last open. f64 for JS-safe export. */
	last_opened: number | null,
};

/**
 *  Frontend-facing summary of one snapshot (specta type).
 *  Timestamps/counts use f64 on the wire: u64 is JS-precision-unsafe and
 *  specta forbids it; all values stay below 2^53.
 */
export type RecoveryEntry = {
	id: string,
	created_at_ms: number | null,
	kind: string,
	scope: string,
	file_count: number,
	size_bytes: number | null,
	warnings: string[],
};

/**
 *  Typed event delivered to the frontend after an invalidation cycle
 *  completed and caches were re-read (tauri-specta generated bindings).
 */
export type RepoChanged = RepoChanged_Serialize | RepoChanged_Deserialize;

/**
 *  Typed event delivered to the frontend after an invalidation cycle
 *  completed and caches were re-read (tauri-specta generated bindings).
 */
export type RepoChanged_Deserialize = {
	repoId: RepoId_Deserialize,
	kinds: string[],
	generation: number,
};

/**
 *  Typed event delivered to the frontend after an invalidation cycle
 *  completed and caches were re-read (tauri-specta generated bindings).
 */
export type RepoChanged_Serialize = {
	repoId: RepoId_Serialize,
	kinds: string[],
	generation: number,
};

/**  A named repository group (flat, v1 — no nesting; PLAN P3.5). */
export type RepoGroup = {
	/**  Stable id (generated at creation, survives renames). */
	id: string,
	name: string,
	/**  Display order (creation order); the UI sorts groups by this. */
	order: number,
};

/**
 *  RepoId: FNV-1a hash of the worktree path. Serialized as a string on the
 *  wire — u64 exceeds JS `Number.MAX_SAFE_INTEGER` and would truncate.
 */
export type RepoId = RepoId_Serialize | RepoId_Deserialize;

/**
 *  RepoId: FNV-1a hash of the worktree path. Serialized as a string on the
 *  wire — u64 exceeds JS `Number.MAX_SAFE_INTEGER` and would truncate.
 */
export type RepoId_Deserialize = string;

/**
 *  RepoId: FNV-1a hash of the worktree path. Serialized as a string on the
 *  wire — u64 exceeds JS `Number.MAX_SAFE_INTEGER` and would truncate.
 */
export type RepoId_Serialize = string;

/**
 *  Per-repo organizational metadata (PLAN P3.5). Entries exist only while
 *  meaningful: [`update_repo`] drops an entry when it becomes the default.
 */
export type RepoMeta = RepoMeta_Serialize | RepoMeta_Deserialize;

/**
 *  Per-repo organizational metadata (PLAN P3.5). Entries exist only while
 *  meaningful: [`update_repo`] drops an entry when it becomes the default.
 */
export type RepoMeta_Deserialize = {
	/**  Group the repo belongs to (`None` = ungrouped). */
	group_id?: string | null,
	/**
	 *  Colorful bookmark (palette id, e.g. `red`/`blue`); `None` = unmarked.
	 *  The palette itself is a frontend display concern.
	 */
	bookmark?: string | null,
};

/**
 *  Per-repo organizational metadata (PLAN P3.5). Entries exist only while
 *  meaningful: [`update_repo`] drops an entry when it becomes the default.
 */
export type RepoMeta_Serialize = {
	/**  Group the repo belongs to (`None` = ungrouped). */
	group_id?: string | null,
	/**
	 *  Colorful bookmark (palette id, e.g. `red`/`blue`); `None` = unmarked.
	 *  The palette itself is a frontend display concern.
	 */
	bookmark?: string | null,
};

/**
 *  Per-repo UI state (PLAN §4.4). The frontend owns the contents; this is a
 *  typed contract so the wire format stays stable. Extend with new
 *  `#[serde(default)]` fields only — never remove/rename existing ones.
 */
export type RepoUiState = RepoUiState_Serialize | RepoUiState_Deserialize;

/**
 *  Per-repo UI state (PLAN §4.4). The frontend owns the contents; this is a
 *  typed contract so the wire format stays stable. Extend with new
 *  `#[serde(default)]` fields only — never remove/rename existing ones.
 */
export type RepoUiState_Deserialize = {
	view?: string | null,
	filter?: string,
	sidebar_collapsed?: string[],
	selected_file?: SelectedFile | null,
	/**  Workspace list mode: `list` (flat sections) or `tree` (path tree). */
	view_mode?: string | null,
	/**  Collapsed directory ids in tree mode. */
	tree_collapsed?: string[],
};

/**
 *  Per-repo UI state (PLAN §4.4). The frontend owns the contents; this is a
 *  typed contract so the wire format stays stable. Extend with new
 *  `#[serde(default)]` fields only — never remove/rename existing ones.
 */
export type RepoUiState_Serialize = {
	view?: string | null,
	filter?: string,
	sidebar_collapsed?: string[],
	selected_file?: SelectedFile | null,
	/**  Workspace list mode: `list` (flat sections) or `tree` (path tree). */
	view_mode?: string | null,
	/**  Collapsed directory ids in tree mode. */
	tree_collapsed?: string[],
};

/**  Selected diff target in the workspace view (frontend-owned UI state). */
export type SelectedFile = {
	path: string,
	/**  `worktree` or `staged` — which diff to show for the file. */
	source: string,
};

/* Tauri Specta runtime */
type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

