// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	/**  Return the detected git capabilities as JSON. */
	gitVersion: () => __TAURI_INVOKE<string>("git_version"),
	/**  Greet command (legacy from template). */
	greet: (name: string) => __TAURI_INVOKE<string>("greet", { name }),
	repoOpen: (path: string) => __TAURI_INVOKE<[RepoId_Serialize, string]>("repo_open", { path }),
	repoClose: (id: RepoId_Deserialize) => __TAURI_INVOKE<null>("repo_close", { id }),
	repoList: () => __TAURI_INVOKE<([RepoId_Serialize, string])[]>("repo_list"),
	gitStatus: (id: RepoId_Deserialize) => __TAURI_INVOKE<FileStatus_Serialize[]>("git_status", { id }),
	gitStage: (id: RepoId_Deserialize, paths: string[]) => __TAURI_INVOKE<null>("git_stage", { id, paths }),
	gitUnstage: (id: RepoId_Deserialize, paths: string[]) => __TAURI_INVOKE<null>("git_unstage", { id, paths }),
	/**
	 *  Discard changes for the given paths, with a recovery snapshot taken
	 *  beforehand (PLAN §4.7 轨道 A) so the operation is undoable.
	 * 
	 *  Scope semantics per path (classification from a fresh status under the
	 *  write gate):
	 *  - untracked → physically deleted (snapshot holds a copy);
	 *  - unmerged (conflict) → full reset to HEAD (`restore --source=HEAD -S -W`);
	 *  - tracked, scope=worktree → `git restore` (staged state kept);
	 *  - tracked, scope=all → `git restore --source=HEAD -S -W` (staged dropped).
	 * 
	 *  Returns the snapshot id for the undo entry, or `None` when nothing was
	 *  discardable. On failure the snapshot is rolled back.
	 */
	gitDiscard: (id: RepoId_Deserialize, paths: string[], scope: string) => __TAURI_INVOKE<string | null>("git_discard", { id, paths, scope }),
	gitCommit: (id: RepoId_Deserialize, message: string, amend: boolean, noVerify: boolean) => __TAURI_INVOKE<CommitResult>("git_commit", { id, message, amend, noVerify }),
	/**
	 *  HEAD commit message (subject + body) for the Amend flow; `None` when
	 *  HEAD is unborn.
	 */
	gitHeadMessage: (id: RepoId_Deserialize) => __TAURI_INVOKE<string | null>("git_head_message", { id }),
	/**  Append paths to `.gitignore` (right-click "ignore" action). */
	gitIgnorePaths: (id: RepoId_Deserialize, paths: string[]) => __TAURI_INVOKE<null>("git_ignore_paths", { id, paths }),
	gitLog: (id: RepoId_Deserialize, limit: number, offset: number, paths: string[] | null) => __TAURI_INVOKE<CommitInfo[]>("git_log", { id, limit, offset, paths }),
	/**
	 *  First page of the commit graph (GraphQuery → GraphCache → GraphLayout;
	 *  the frontend renders SVG). Returns the loaded rows (≤ 500).
	 */
	gitGraph: (id: RepoId_Deserialize, filter: {
	/**
	 *  Message search (`--grep -i`). A pure-hex prefix of ≥ 4 chars is
	 *  treated as a hash jump instead: it resolves via `rev-parse` and the
	 *  graph starts at that commit.
	 */
	text: string | null,
	/**  Author substring (`--author -i`). */
	author: string | null,
	/**  `--since` (git date, e.g. `2026-01-01`). */
	since: string | null,
	/**  `--until`. */
	until: string | null,
	/**  History touching any of these paths. */
	paths: string[],
} | null) => __TAURI_INVOKE<GraphPage>("git_graph", { id, filter }),
	/**
	 *  Next graph page (`start` = row index of the returned rows in the full
	 *  graph; `start = 0` means the cache was rebuilt → replace the list).
	 */
	gitGraphMore: (id: RepoId_Deserialize, filter: {
	/**
	 *  Message search (`--grep -i`). A pure-hex prefix of ≥ 4 chars is
	 *  treated as a hash jump instead: it resolves via `rev-parse` and the
	 *  graph starts at that commit.
	 */
	text: string | null,
	/**  Author substring (`--author -i`). */
	author: string | null,
	/**  `--since` (git date, e.g. `2026-01-01`). */
	since: string | null,
	/**  `--until`. */
	until: string | null,
	/**  History touching any of these paths. */
	paths: string[],
} | null) => __TAURI_INVOKE<GraphPage>("git_graph_more", { id, filter }),
	/**
	 *  Commit metadata + changed files (详情面板)。Merge commits diff against
	 *  the first parent; root commits against the empty tree.
	 */
	gitCommitDetail: (id: RepoId_Deserialize, hash: string) => __TAURI_INVOKE<CommitDetail>("git_commit_detail", { id, hash }),
	/**
	 *  Cherry-pick the given commits onto HEAD, in list order (oldest first).
	 *  Conflicts surface as git errors — the visual conflict flow is P8.
	 */
	gitCherryPick: (id: RepoId_Deserialize, hashes: string[]) => __TAURI_INVOKE<null>("git_cherry_pick", { id, hashes }),
	/**  Revert the given commits (`revert --no-edit`), in list order. */
	gitRevert: (id: RepoId_Deserialize, hashes: string[]) => __TAURI_INVOKE<null>("git_revert", { id, hashes }),
	/**
	 *  Squash the selected commits into one (`reset --soft <base>` + one
	 *  commit). v1 constraint (validated here): the selection must be exactly
	 *  the newest K commits of the first-parent chain from HEAD, none of them
	 *  a merge, and a parent must remain (the whole history cannot vanish).
	 *  Recovery-wise the move is visible in the reflog; the dedicated backup
	 *  ref flow arrives with ResetRecovery in P6.
	 */
	gitSquash: (id: RepoId_Deserialize, hashes: string[], message: string) => __TAURI_INVOKE<null>("git_squash", { id, hashes, message }),
	/**
	 *  Restore file(s) from a revision into the worktree (P5 从历史恢复此文件
	 *  版本)，after a track-A recovery snapshot so the overwrite is undoable.
	 *  Returns the snapshot id for the undo toast.
	 */
	gitRestoreFileVersion: (id: RepoId_Deserialize, rev: string, paths: string[]) => __TAURI_INVOKE<string | null>("git_restore_file_version", { id, rev, paths }),
	/**
	 *  Create a branch (used by the detached-HEAD guidance banner and later
	 *  the branch panel).
	 */
	gitCreateBranch: (id: RepoId_Deserialize, name: string, startPoint: string | null) => __TAURI_INVOKE<null>("git_create_branch", { id, name, startPoint }),
	/**
	 *  Parse a diff for the given source/paths into a [`DiffModel`], cache it in
	 *  the RepoManager session and return it with its cache id.
	 * 
	 *  Untracked worktree paths never appear in `git diff`; they are synthesized
	 *  as pure-addition files (P4) so line-level stage/discard works on them.
	 *  The model id is what line-level operations send back — Rust rebuilds the
	 *  patch from the same cached model (同源，杜绝双端解析漂移).
	 */
	gitDiff: (id: RepoId_Deserialize, source: DiffSource, oldRev: string | null, newRev: string | null, paths: string[] | null, contextLines: number | null, ignoreWhitespace: boolean | null) => __TAURI_INVOKE<DiffModel>("git_diff", { id, source, oldRev, newRev, paths, contextLines, ignoreWhitespace }),
	/**
	 *  Stage the selected lines of one file into the index
	 *  (`git apply --cached`; P4 行级暂存).
	 */
	gitStageLines: (id: RepoId_Deserialize, modelId: number, path: string, selections: LineSelection[]) => __TAURI_INVOKE<null>("git_stage_lines", { id, modelId, path, selections }),
	/**
	 *  Discard the selected lines from the worktree (`git apply --reverse`),
	 *  with a whole-file recovery snapshot taken first (§4.7 轨道 A) so the
	 *  operation is undoable. Returns the snapshot id for the undo entry.
	 */
	gitDiscardLines: (id: RepoId_Deserialize, modelId: number, path: string, selections: LineSelection[]) => __TAURI_INVOKE<string | null>("git_discard_lines", { id, modelId, path, selections }),
	/**
	 *  Remove the selected lines from the index
	 *  (`git apply --cached --reverse`; P4 行级取消暂存).
	 */
	gitUnstageLines: (id: RepoId_Deserialize, modelId: number, path: string, selections: LineSelection[]) => __TAURI_INVOKE<null>("git_unstage_lines", { id, modelId, path, selections }),
	/**
	 *  Content of one file revision for the image diff: `rev = None` reads the
	 *  worktree file, otherwise `git cat-file blob <rev>:<path>` (e.g. `HEAD`,
	 *  `:0` for the index, or a commit-ish). Oversized files return `data: null`.
	 */
	gitFileContent: (id: RepoId_Deserialize, path: string, rev: string | null) => __TAURI_INVOKE<FileContent>("git_file_content", { id, path, rev }),
	gitBranches: (id: RepoId_Deserialize) => __TAURI_INVOKE<BranchInfo[]>("git_branches", { id }),
	gitCheckoutBranch: (id: RepoId_Deserialize, name: string) => __TAURI_INVOKE<null>("git_checkout_branch", { id, name }),
	recoveryList: (id: RepoId_Deserialize) => __TAURI_INVOKE<RecoveryEntry[]>("recovery_list", { id }),
	recoveryRestore: (id: RepoId_Deserialize, snapshotId: string) => __TAURI_INVOKE<null>("recovery_restore", { id, snapshotId }),
	recoveryDelete: (id: RepoId_Deserialize, snapshotId: string) => __TAURI_INVOKE<null>("recovery_delete", { id, snapshotId }),
	workspaceRecents: () => __TAURI_INVOKE<RecentRepo[]>("workspace_recents"),
	workspaceTouchRecent: (path: string, name: string) => __TAURI_INVOKE<null>("workspace_touch_recent", { path, name }),
	workspaceForgetRecent: (path: string) => __TAURI_INVOKE<null>("workspace_forget_recent", { path }),
	workspaceLoadState: (repoPath: string) => __TAURI_INVOKE<{
	view?: string | null,
	filter?: string,
	sidebar_collapsed?: string[],
	selected_file?: SelectedFile | null,
	/**  Workspace list mode: `list` (flat sections) or `tree` (path tree). */
	view_mode?: string | null,
	/**  Collapsed directory ids in tree mode. */
	tree_collapsed?: string[],
} | null>("workspace_load_state", { repoPath }),
	workspaceSaveState: (repoPath: string, state: RepoUiState_Deserialize) => __TAURI_INVOKE<null>("workspace_save_state", { repoPath, state }),
	/**  Load the full groups file (groups + per-repo metadata). */
	workspaceGroups: () => __TAURI_INVOKE<GroupsFile_Serialize>("workspace_groups"),
	/**  Create a group (`id: None`) or rename an existing one (`id: Some`). */
	workspaceUpsertGroup: (id: string | null, name: string) => __TAURI_INVOKE<RepoGroup>("workspace_upsert_group", { id, name }),
	/**  Delete a group; member repos fall back to ungrouped (stars are kept). */
	workspaceDeleteGroup: (id: string) => __TAURI_INVOKE<null>("workspace_delete_group", { id }),
	/**
	 *  Set the organizational metadata of one repo (group membership and/or
	 *  star; full replace).
	 */
	workspaceUpdateRepo: (path: string, meta: RepoMeta_Deserialize) => __TAURI_INVOKE<null>("workspace_update_repo", { path, meta }),
};

/** Events */
export const events = {
	appOpenPaths: makeEvent<AppOpenPaths>("app-open-paths"),
	repoChanged: makeEvent<RepoChanged_Deserialize>("repo-changed"),
};

/* Types */
/**  Application-wide error type. */
export type AppError = { code: "io"; source: string; detail: string | null } | { code: "git_command"; command: string; stderr: string; stdout: string; detail: string | null } | { code: "git_version_too_old"; found: string; required: string } | { code: "invalid_repo"; path: string } | { code: "operation_cancelled" } | { code: "credential_cancelled" } | 
/**
 *  The cached DiffModel referenced by a line-level operation is gone
 *  (invalidated by a watcher event or evicted). The UI must re-fetch
 *  the diff and retry (PLAN P4: 同源保证 — 不重建，宁可拒绝).
 */
{ code: "diff_model_expired" } | { code: "parse"; message: string } | { code: "internal"; message: string } | { code: "not_implemented"; feature: string };

/**
 *  Emitted to the frontend when a second app instance was launched with
 *  repository paths on its command line (single-instance plugin, P2).
 */
export type AppOpenPaths = {
	paths: string[],
};

export type BranchInfo = {
	name: string,
	full_name: string,
	upstream: string | null,
	ahead: number,
	behind: number,
	current: boolean,
	detached: boolean,
};

/**  Commit metadata + changed files (P5 提交详情). */
export type CommitDetail = {
	commit: CommitInfo,
	/**
	 *  First parent, `None` for a root commit (diff then uses the empty
	 *  tree on the frontend side).
	 */
	parent: string | null,
	files: CommitFileStat[],
};

/**  One changed file of a commit (P5 提交详情变更列表). */
export type CommitFileStat = {
	/**
	 *  git name-status letter: `A` added, `M` modified, `D` deleted,
	 *  `T` typechange, `R` renamed, `C` copied, `U` unmerged.
	 */
	status: string,
	/**  Rename/copy similarity score (e.g. `93` for `R93`), if any. */
	score: number | null,
	/**  Destination path (for renames/copies the new name). */
	path: string,
	/**  Source path for renames/copies. */
	orig_path: string | null,
};

export type CommitInfo = {
	hash: string,
	short_hash: string,
	author: string,
	email: string,
	date: string,
	message: string,
	refs: string[],
	parents: string[],
};

export type CommitResult = {
	hash: string,
	short_hash: string,
	message: string,
};

export type DiffFile = {
	old_path: string | null,
	new_path: string | null,
	similarity: number | null,
	binary: boolean,
	hunks: DiffHunk[],
};

export type DiffHunk = {
	old_start: number,
	old_count: number,
	new_start: number,
	new_count: number,
	header: string,
	lines: DiffLine[],
};

export type DiffLine = {
	content: string,
	left_no: number | null,
	right_no: number | null,
	kind: DiffLineKind,
	/**
	 *  The line is followed by `\\ No newline at end of file`: the file on
	 *  this line's side ends without a trailing newline. Only the genuine
	 *  last line of a side can carry this; the patch builder uses it to
	 *  reproduce correct `\\ No newline` markers (P4 行级暂存边界用例).
	 */
	no_eol?: boolean,
};

export type DiffLineKind = "context" | "add" | "remove" | "header";

export type DiffModel = {
	/**
	 *  Identity of the cached model on the Rust side (PLAN P4: 行级操作由前端
	 *  上报 model id + 行号，Rust 从同一模型构造 patch，杜绝双端解析漂移).
	 *  0 = not cached (parse-time default).
	 */
	id?: number,
	source: DiffSource,
	old_revision: string | null,
	new_revision: string | null,
	files: DiffFile[],
};

export type DiffSource = "worktree" | "staged" | "commit" | "stash";

/**
 *  Content of one file revision (worktree or a git object), base64-encoded
 *  for the wire; `data` is `None` when the file exceeds the transfer cap.
 */
export type FileContent = {
	/**
	 *  Saturates at `u32::MAX` for absurd sizes (the UI only needs a
	 *  "too large" signal past the transfer cap).
	 */
	size: number,
	data: string | null,
};

export type FileStatus = FileStatus_Serialize | FileStatus_Deserialize;

export type FileStatus_Deserialize = {
	path: string,
	status: string,
	orig_path: string | null,
	submodule: boolean,
	/**  Submodule with modified content (porcelain v2 `sub = S`). */
	submodule_dirty: boolean,
	/**  Submodule whose checked-in commit differs from the index (`sub = M`). */
	submodule_commit_changed: boolean,
	/**
	 *  The worktree change consists only of line-ending differences
	 *  (CRLF/LF); detected via the `--ignore-cr-at-eol` numstat diff.
	 */
	eol_only: boolean,
	staged: boolean,
	unstaged: boolean,
	untracked: boolean,
	/**  skip-worktree (porcelain v2 XY contains `S`). */
	skipped: boolean,
	conflict: boolean,
};

export type FileStatus_Serialize = {
	path: string,
	status: string,
	orig_path?: string | null,
	submodule: boolean,
	/**  Submodule with modified content (porcelain v2 `sub = S`). */
	submodule_dirty: boolean,
	/**  Submodule whose checked-in commit differs from the index (`sub = M`). */
	submodule_commit_changed: boolean,
	/**
	 *  The worktree change consists only of line-ending differences
	 *  (CRLF/LF); detected via the `--ignore-cr-at-eol` numstat diff.
	 */
	eol_only: boolean,
	staged: boolean,
	unstaged: boolean,
	untracked: boolean,
	/**  skip-worktree (porcelain v2 XY contains `S`). */
	skipped: boolean,
	conflict: boolean,
};

/**  One edge segment drawn within a single commit row. */
export type GraphEdge = {
	/**  Lane (column) where the edge starts on this row. */
	from: number,
	/**  Lane (column) where the edge ends on this row. */
	to: number,
	/**  The edge starts at this row's node (mid-height, lower half). */
	from_node: boolean,
	/**  The edge ends at this row's node (mid-height, upper half). */
	to_node: boolean,
};

/**  Search/filter for the history graph query (PLAN P5 搜索/筛选). */
export type GraphFilter = {
	/**
	 *  Message search (`--grep -i`). A pure-hex prefix of ≥ 4 chars is
	 *  treated as a hash jump instead: it resolves via `rev-parse` and the
	 *  graph starts at that commit.
	 */
	text: string | null,
	/**  Author substring (`--author -i`). */
	author: string | null,
	/**  `--since` (git date, e.g. `2026-01-01`). */
	since: string | null,
	/**  `--until`. */
	until: string | null,
	/**  History touching any of these paths. */
	paths: string[],
};

/**
 *  One page of the commit graph served by the GraphCache (P5). `start` is
 *  the row index of `rows[0]` within the full graph: `0` means the cache
 *  was rebuilt and the frontend must replace its list, otherwise the rows
 *  append after the previously loaded ones.
 */
export type GraphPage = {
	rows: GraphRow[],
	start: number,
	/**  `git log` exhausted — no further pages. */
	complete: boolean,
	/**  Lanes used so far (SVG column count). */
	width: number,
};

/**
 *  One rendered row of the commit graph: the commit plus its lane and the
 *  edge segments crossing the row.
 */
export type GraphRow = {
	commit: CommitInfo,
	/**  Column of this commit's node. */
	lane: number,
	edges: GraphEdge[],
};

/**
 *  `workspaces/groups.json` — the long-lived organizational layer over the
 *  repo collection. Unlike `recents.json` (bounded recently-opened list),
 *  group membership and stars must survive recents truncation, hence a
 *  separate file (PLAN P3.5).
 */
export type GroupsFile = GroupsFile_Serialize | GroupsFile_Deserialize;

/**
 *  `workspaces/groups.json` — the long-lived organizational layer over the
 *  repo collection. Unlike `recents.json` (bounded recently-opened list),
 *  group membership and stars must survive recents truncation, hence a
 *  separate file (PLAN P3.5).
 */
export type GroupsFile_Deserialize = {
	version?: number,
	groups?: RepoGroup[],
	/**
	 *  Resolved repo path → metadata. Keys use the resolved worktree root
	 *  (same normalization as `RepoId`) to avoid Windows case ambiguity.
	 */
	repos?: { [key in string]: RepoMeta_Deserialize },
};

/**
 *  `workspaces/groups.json` — the long-lived organizational layer over the
 *  repo collection. Unlike `recents.json` (bounded recently-opened list),
 *  group membership and stars must survive recents truncation, hence a
 *  separate file (PLAN P3.5).
 */
export type GroupsFile_Serialize = {
	version: number,
	groups: RepoGroup[],
	/**
	 *  Resolved repo path → metadata. Keys use the resolved worktree root
	 *  (same normalization as `RepoId`) to avoid Windows case ambiguity.
	 */
	repos: { [key in string]: RepoMeta_Serialize },
};

/**
 *  One selected diff line for line-level operations (P4 行级暂存): indices
 *  into the cached [`DiffModel`] the frontend is displaying.
 */
export type LineSelection = {
	/**  Index into `DiffFile.hunks`. */
	hunk: number,
	/**  Index into `DiffHunk.lines`. */
	line: number,
};

export type RecentRepo = {
	path: string,
	name: string,
	/**  Unix timestamp (seconds) of the last open. f64 for JS-safe export. */
	last_opened: number | null,
};

/**
 *  Frontend-facing summary of one snapshot (specta type).
 *  Timestamps/counts use f64 on the wire: u64 is JS-precision-unsafe and
 *  specta forbids it; all values stay below 2^53.
 */
export type RecoveryEntry = {
	id: string,
	created_at_ms: number | null,
	kind: string,
	scope: string,
	file_count: number,
	size_bytes: number | null,
	warnings: string[],
};

/**
 *  Typed event delivered to the frontend after an invalidation cycle
 *  completed and caches were re-read (tauri-specta generated bindings).
 */
export type RepoChanged = RepoChanged_Serialize | RepoChanged_Deserialize;

/**
 *  Typed event delivered to the frontend after an invalidation cycle
 *  completed and caches were re-read (tauri-specta generated bindings).
 */
export type RepoChanged_Deserialize = {
	repoId: RepoId_Deserialize,
	kinds: string[],
	generation: number,
};

/**
 *  Typed event delivered to the frontend after an invalidation cycle
 *  completed and caches were re-read (tauri-specta generated bindings).
 */
export type RepoChanged_Serialize = {
	repoId: RepoId_Serialize,
	kinds: string[],
	generation: number,
};

/**  A named repository group (flat, v1 — no nesting; PLAN P3.5). */
export type RepoGroup = {
	/**  Stable id (generated at creation, survives renames). */
	id: string,
	name: string,
	/**  Display order (creation order); the UI sorts groups by this. */
	order: number,
};

/**
 *  RepoId: FNV-1a hash of the worktree path. Serialized as a string on the
 *  wire — u64 exceeds JS `Number.MAX_SAFE_INTEGER` and would truncate.
 */
export type RepoId = RepoId_Serialize | RepoId_Deserialize;

/**
 *  RepoId: FNV-1a hash of the worktree path. Serialized as a string on the
 *  wire — u64 exceeds JS `Number.MAX_SAFE_INTEGER` and would truncate.
 */
export type RepoId_Deserialize = string;

/**
 *  RepoId: FNV-1a hash of the worktree path. Serialized as a string on the
 *  wire — u64 exceeds JS `Number.MAX_SAFE_INTEGER` and would truncate.
 */
export type RepoId_Serialize = string;

/**
 *  Per-repo organizational metadata (PLAN P3.5). Entries exist only while
 *  meaningful: [`update_repo`] drops an entry when it becomes the default.
 */
export type RepoMeta = RepoMeta_Serialize | RepoMeta_Deserialize;

/**
 *  Per-repo organizational metadata (PLAN P3.5). Entries exist only while
 *  meaningful: [`update_repo`] drops an entry when it becomes the default.
 */
export type RepoMeta_Deserialize = {
	/**  Group the repo belongs to (`None` = ungrouped). */
	group_id?: string | null,
	/**
	 *  Colorful bookmark (palette id, e.g. `red`/`blue`); `None` = unmarked.
	 *  The palette itself is a frontend display concern.
	 */
	bookmark?: string | null,
};

/**
 *  Per-repo organizational metadata (PLAN P3.5). Entries exist only while
 *  meaningful: [`update_repo`] drops an entry when it becomes the default.
 */
export type RepoMeta_Serialize = {
	/**  Group the repo belongs to (`None` = ungrouped). */
	group_id?: string | null,
	/**
	 *  Colorful bookmark (palette id, e.g. `red`/`blue`); `None` = unmarked.
	 *  The palette itself is a frontend display concern.
	 */
	bookmark?: string | null,
};

/**
 *  Per-repo UI state (PLAN §4.4). The frontend owns the contents; this is a
 *  typed contract so the wire format stays stable. Extend with new
 *  `#[serde(default)]` fields only — never remove/rename existing ones.
 */
export type RepoUiState = RepoUiState_Serialize | RepoUiState_Deserialize;

/**
 *  Per-repo UI state (PLAN §4.4). The frontend owns the contents; this is a
 *  typed contract so the wire format stays stable. Extend with new
 *  `#[serde(default)]` fields only — never remove/rename existing ones.
 */
export type RepoUiState_Deserialize = {
	view?: string | null,
	filter?: string,
	sidebar_collapsed?: string[],
	selected_file?: SelectedFile | null,
	/**  Workspace list mode: `list` (flat sections) or `tree` (path tree). */
	view_mode?: string | null,
	/**  Collapsed directory ids in tree mode. */
	tree_collapsed?: string[],
};

/**
 *  Per-repo UI state (PLAN §4.4). The frontend owns the contents; this is a
 *  typed contract so the wire format stays stable. Extend with new
 *  `#[serde(default)]` fields only — never remove/rename existing ones.
 */
export type RepoUiState_Serialize = {
	view?: string | null,
	filter?: string,
	sidebar_collapsed?: string[],
	selected_file?: SelectedFile | null,
	/**  Workspace list mode: `list` (flat sections) or `tree` (path tree). */
	view_mode?: string | null,
	/**  Collapsed directory ids in tree mode. */
	tree_collapsed?: string[],
};

/**  Selected diff target in the workspace view (frontend-owned UI state). */
export type SelectedFile = {
	path: string,
	/**  `worktree` or `staged` — which diff to show for the file. */
	source: string,
};

/* Tauri Specta runtime */
type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

