// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	/**  Return the detected git capabilities as JSON. */
	gitVersion: () => __TAURI_INVOKE<string>("git_version"),
	/**  Greet command (legacy from template). */
	greet: (name: string) => __TAURI_INVOKE<string>("greet", { name }),
	repoOpen: (path: string) => __TAURI_INVOKE<[RepoId_Serialize, string]>("repo_open", { path }),
	repoClose: (id: RepoId_Deserialize) => __TAURI_INVOKE<null>("repo_close", { id }),
	repoList: () => __TAURI_INVOKE<([RepoId_Serialize, string])[]>("repo_list"),
	gitStatus: (id: RepoId_Deserialize) => __TAURI_INVOKE<FileStatus_Serialize[]>("git_status", { id }),
	gitStage: (id: RepoId_Deserialize, paths: string[]) => __TAURI_INVOKE<null>("git_stage", { id, paths }),
	gitUnstage: (id: RepoId_Deserialize, paths: string[]) => __TAURI_INVOKE<null>("git_unstage", { id, paths }),
	gitDiscard: (id: RepoId_Deserialize, paths: string[]) => __TAURI_INVOKE<null>("git_discard", { id, paths }),
	gitCommit: (id: RepoId_Deserialize, message: string, amend: boolean, noVerify: boolean) => __TAURI_INVOKE<CommitResult>("git_commit", { id, message, amend, noVerify }),
	gitLog: (id: RepoId_Deserialize, limit: number, offset: number, paths: string[] | null) => __TAURI_INVOKE<CommitInfo[]>("git_log", { id, limit, offset, paths }),
	gitDiff: (id: RepoId_Deserialize, source: string, oldRev: string | null, newRev: string | null, paths: string[] | null) => __TAURI_INVOKE<DiffModel>("git_diff", { id, source, oldRev, newRev, paths }),
	gitBranches: (id: RepoId_Deserialize) => __TAURI_INVOKE<BranchInfo[]>("git_branches", { id }),
	gitCheckoutBranch: (id: RepoId_Deserialize, name: string) => __TAURI_INVOKE<null>("git_checkout_branch", { id, name }),
	workspaceRecents: () => __TAURI_INVOKE<RecentRepo[]>("workspace_recents"),
	workspaceTouchRecent: (path: string, name: string) => __TAURI_INVOKE<null>("workspace_touch_recent", { path, name }),
	workspaceForgetRecent: (path: string) => __TAURI_INVOKE<null>("workspace_forget_recent", { path }),
	workspaceLoadState: (repoPath: string) => __TAURI_INVOKE<{
	view?: string | null,
	filter?: string,
	sidebar_collapsed?: string[],
	selected_file?: SelectedFile | null,
} | null>("workspace_load_state", { repoPath }),
	workspaceSaveState: (repoPath: string, state: RepoUiState_Deserialize) => __TAURI_INVOKE<null>("workspace_save_state", { repoPath, state }),
};

/** Events */
export const events = {
	appOpenPaths: makeEvent<AppOpenPaths>("app-open-paths"),
	repoChanged: makeEvent<RepoChanged_Deserialize>("repo-changed"),
};

/* Types */
/**  Application-wide error type. */
export type AppError = { code: "io"; source: string; detail: string | null } | { code: "git_command"; command: string; stderr: string; stdout: string; detail: string | null } | { code: "git_version_too_old"; found: string; required: string } | { code: "invalid_repo"; path: string } | { code: "operation_cancelled" } | { code: "credential_cancelled" } | { code: "parse"; message: string } | { code: "internal"; message: string } | { code: "not_implemented"; feature: string };

/**
 *  Emitted to the frontend when a second app instance was launched with
 *  repository paths on its command line (single-instance plugin, P2).
 */
export type AppOpenPaths = {
	paths: string[],
};

export type BranchInfo = {
	name: string,
	full_name: string,
	upstream: string | null,
	ahead: number,
	behind: number,
	current: boolean,
	detached: boolean,
};

export type CommitInfo = {
	hash: string,
	short_hash: string,
	author: string,
	email: string,
	date: string,
	message: string,
	refs: string[],
	parents: string[],
};

export type CommitResult = {
	hash: string,
	short_hash: string,
	message: string,
};

export type DiffFile = {
	old_path: string | null,
	new_path: string | null,
	similarity: number | null,
	binary: boolean,
	hunks: DiffHunk[],
};

export type DiffHunk = {
	old_start: number,
	old_count: number,
	new_start: number,
	new_count: number,
	header: string,
	lines: DiffLine[],
};

export type DiffLine = {
	content: string,
	left_no: number | null,
	right_no: number | null,
	kind: DiffLineKind,
};

export type DiffLineKind = "context" | "add" | "remove" | "header";

export type DiffModel = {
	source: DiffSource,
	old_revision: string | null,
	new_revision: string | null,
	files: DiffFile[],
};

export type DiffSource = "worktree" | "staged" | "commit" | "stash";

export type FileStatus = FileStatus_Serialize | FileStatus_Deserialize;

export type FileStatus_Deserialize = {
	path: string,
	status: string,
	orig_path: string | null,
	submodule: boolean,
	staged: boolean,
	unstaged: boolean,
	untracked: boolean,
	skipped: boolean,
	conflict: boolean,
};

export type FileStatus_Serialize = {
	path: string,
	status: string,
	orig_path?: string | null,
	submodule: boolean,
	staged: boolean,
	unstaged: boolean,
	untracked: boolean,
	skipped: boolean,
	conflict: boolean,
};

export type RecentRepo = {
	path: string,
	name: string,
	/**  Unix timestamp (seconds) of the last open. f64 for JS-safe export. */
	last_opened: number | null,
};

/**
 *  Typed event delivered to the frontend after an invalidation cycle
 *  completed and caches were re-read (tauri-specta generated bindings).
 */
export type RepoChanged = RepoChanged_Serialize | RepoChanged_Deserialize;

/**
 *  Typed event delivered to the frontend after an invalidation cycle
 *  completed and caches were re-read (tauri-specta generated bindings).
 */
export type RepoChanged_Deserialize = {
	repoId: RepoId_Deserialize,
	kinds: string[],
	generation: number,
};

/**
 *  Typed event delivered to the frontend after an invalidation cycle
 *  completed and caches were re-read (tauri-specta generated bindings).
 */
export type RepoChanged_Serialize = {
	repoId: RepoId_Serialize,
	kinds: string[],
	generation: number,
};

/**
 *  RepoId: FNV-1a hash of the worktree path. Serialized as a string on the
 *  wire — u64 exceeds JS `Number.MAX_SAFE_INTEGER` and would truncate.
 */
export type RepoId = RepoId_Serialize | RepoId_Deserialize;

/**
 *  RepoId: FNV-1a hash of the worktree path. Serialized as a string on the
 *  wire — u64 exceeds JS `Number.MAX_SAFE_INTEGER` and would truncate.
 */
export type RepoId_Deserialize = string;

/**
 *  RepoId: FNV-1a hash of the worktree path. Serialized as a string on the
 *  wire — u64 exceeds JS `Number.MAX_SAFE_INTEGER` and would truncate.
 */
export type RepoId_Serialize = string;

/**
 *  Per-repo UI state (PLAN §4.4). The frontend owns the contents; this is a
 *  typed contract so the wire format stays stable. Extend with new
 *  `#[serde(default)]` fields only — never remove/rename existing ones.
 */
export type RepoUiState = RepoUiState_Serialize | RepoUiState_Deserialize;

/**
 *  Per-repo UI state (PLAN §4.4). The frontend owns the contents; this is a
 *  typed contract so the wire format stays stable. Extend with new
 *  `#[serde(default)]` fields only — never remove/rename existing ones.
 */
export type RepoUiState_Deserialize = {
	view?: string | null,
	filter?: string,
	sidebar_collapsed?: string[],
	selected_file?: SelectedFile | null,
};

/**
 *  Per-repo UI state (PLAN §4.4). The frontend owns the contents; this is a
 *  typed contract so the wire format stays stable. Extend with new
 *  `#[serde(default)]` fields only — never remove/rename existing ones.
 */
export type RepoUiState_Serialize = {
	view?: string | null,
	filter?: string,
	sidebar_collapsed?: string[],
	selected_file?: SelectedFile | null,
};

/**  Selected diff target in the workspace view (frontend-owned UI state). */
export type SelectedFile = {
	path: string,
	/**  `worktree` or `staged` — which diff to show for the file. */
	source: string,
};

/* Tauri Specta runtime */
type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

